# -*- coding: utf-8 -*-
"""pycaret_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bHS7piFNKZcwOzeceAQ4zwSq8Z9zQmFt
"""

!pip install pycaret
#!pip install pycaret[full]

pip install scikit-learn-intelex

# load dataset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load your dataset
df = pd.read_csv('linux_memory1.csv')

# Extract features and labels
X = df.drop(columns=['label','type'])
y = df['label']

# Plot class distribution histogram
plt.figure(figsize=(8, 6))
ax = sns.countplot(x='label', data=df)  # Corrected 'class' to 'label'
plt.title('Class Distribution Histogram')
plt.xlabel('Class')
plt.ylabel('Count')

# Add numbers to the head of each column
for p in ax.patches:
    ax.annotate(f'{p.get_height()}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', xytext=(0, 10), textcoords='offset points')

plt.show()

# Show dataset summary
dataset_summary = df.describe(include='all')

# PyCaret Setup
from pycaret.classification import *

# setup with GPU support
clf1 = setup(data=X, target=y, use_gpu=True)

# Compare models
best = compare_models()

# Evaluate best model
evaluate_model(best)

print(best)
df.describe(include='all')

plot_model(best, plot = 'auc')

plot_model(best, plot = 'confusion_matrix')

plot_model(best, plot = 'learning')

# functional API
save_model(best, 'my_best_pipeline')